### ISSUE TITLE
Create link to Immunefi bug bounty program for main page

### ISSUE THREAD

**Issue by Luna5-threshold** [threshold-network/website#80]
In order to showcase Threshold's bug bounty program by immunefi, we need to add a visible link or banner to the main page. 

- Here are some suggestions on how other projects have introduced the link to their immunefi bounties -> [Immunefi Website Guide for Immunefi Bug Bounty Clients.pdf](https://github.com/threshold-network/splash-page/files/11396547/Immunefi.Website.Guide.for.Immunefi.Bug.Bounty.Clients.pdf)

- This is Threshold Network's bug bounty program link -> [https://immunefi.com/bounty/thresholdnetwork/](https://immunefi.com/bounty/thresholdnetwork/)

- And here you can find Immunefi's brand assets to use in our page -> [https://drive.google.com/drive/u/0/folders/1fKFxkLccjKwvVD6YWPeWJgCxs76z5Pwf](https://drive.google.com/drive/u/0/folders/1fKFxkLccjKwvVD6YWPeWJgCxs76z5Pwf)

```[tasklist]
### Tasks
- [ ] https://github.com/threshold-network/website/pull/97
```

**Comment by erdogan** [comment]
@sashatanase bringing this to your attention - could be a good warm up task for Sorin

**Comment by sashatanase** [comment]
@Luna5-threshold are we looking to display this banner on the Threshold Network Website or on the Immunefi website?

**Comment by Luna5-threshold** [comment]
@sashatanase information on the immunefi bug bounty for Threshold should be displayed in the threshold network page. I leave it to your experts if you want to create a banner or you prefer to capture attention using other means, but it should be linked to the immunefi page for threshold as indicated above (it has all the details for the hackers to consider).

**Comment by sashatanase** [comment]
How long is this bug bounty going to be active? Is this permanent or temporary?

**Comment by Luna5-threshold** [comment]
Permanent as far as I am aware, what is more, we will be adding more products to it, so the bug bounty will cover thUSD and taco when they launch (and any other threshold products in the future)

**Comment by sashatanase** [comment]
Okay, great, then let me write some more details so Sorin can take over it. 

Sorin we need to add a new section in the Threshold Network website Figma File [here](https://www.figma.com/file/q8Aef9yTHUipGdnqzmh6UG/Website?type=design&node-id=2604%3A30701&mode=design&t=BFFVrzObyvTQfgMf-1)

We may need to add a subsection on the homepage with the Bug Bounty supported by Immunefi, however, if you find a better solution feel free to showcase it.

**Comment by SorinQ** [comment]
Hi all, thank you for all the information. 
Just as an update, I'm currently analyzing and working on it.

**Comment by SorinQ** [comment]
### Proposed Solution
Create a new banner section on the Threshold website homepage.
The CTA will redirect users to our Bounty program hosted on the Immunefi platform:    
https://immunefi.com/bounty/thresholdnetwork/

<img width="794" alt="Screenshot 2023-08-01 at 13 58 29" src="https://github.com/threshold-network/website/assets/37292909/53969f72-6f57-4602-9d5a-2e9c33182ca0">

### Design
<img width="1255" alt="Screenshot 2023-08-01 at 13 58 13" src="https://github.com/threshold-network/website/assets/37292909/dffaccaf-dec2-4704-ae96-b1b819fde049">


We will also add a link button in the footer under **General** 
<img width="1469" alt="Screenshot 2023-08-01 at 13 58 20" src="https://github.com/threshold-network/website/assets/37292909/85a76566-909c-4110-84f6-ad31eadb6068">


Figma link [here](https://www.figma.com/file/OUdSfHsmgV8EJpWxAzXjl5/Design-Exploration?type=design&node-id=167-18572&mode=design&t=2GJVx1gw9Eb2TYak-4)

**Comment by SorinQ** [comment]
Exploration

<img width="1250" alt="Screenshot 2023-08-01 at 14 07 07" src="https://github.com/threshold-network/website/assets/37292909/b4cb012e-f1eb-4837-899d-a3bc51c368d8">

**Comment by SorinQ** [comment]
Everything looking good! @michalsmiarowski 
Just one last _subjective_ comment, please feel free to dismiss it if you consider otherwise:

In the text 'Spot security risks, claim your prize. No KYC, no fuss." could we push the "No KYC, no fuss." entirely to the second line?
